{% set name = "xontrib-kitty" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scopatz/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: f11a8a13c494d157040b91ffa4b94b9de6ab5aa4eb7ffb15696fd51aa2d93967

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - xonsh
    # note that kitty and matplotlib are optional dependncies

test:
  commands:
    - xonsh -c "xontrib load kitty"

about:
  home: https://github.com/scopatz/xontrib-kitty
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Xonsh hooks for the Kitty terminal emulator'

extra:
  recipe-maintainers:
    - scopatz
