travis:
  secure:
    BINSTAR_TOKEN: Qtpz5pGV5cbvjHlt/Jx3fIGFRFKMi0iUzv53P9UDbUvYNHpfgVdy+dBdOn8O8qTzztzFNzqEjxHxyb58c4c1NLqJDyQl4dlWV9ae97OM5PCZlAO4mblcF5SR2yeGi00T/i1mVakKvjLc2ZMwrvEu5uAhBGD7v0w1zt48kweAsT94p+xkOHpebFT9f6zt6hhlEx1kzwu/XsbYyvRshdhAHeYKgVZZX8y4MrUpoooWlarFE9cXw6R86oxHErGVCUR4qJGAHr449z1/ycf1qAY5JssaSZUL7jIKcS5Qi61k+1h0aYsxO9c6PvUIYSKoTwgEN/RbrFdCxHE0smXAgTuFemHsFWOYdifTzesfi7Jp1b9zzb8zTMMk0z997anVZbVl7HGgpoxXRueJbO+vfr9cbulOxeevv69ivwgI/FpOwxreeqOWSooqDtPOWPBu0LpKuV+ehLcK46wK7+f04EAB53TYlJzGKci3Dne49obZdn4AGLrYu/05TxVeb8kbvPhRzIkalQRH6UdpQM5YTu+LVSu0sC079Y56vxLH1t64RL9SYOnvOt6FudBoX3vhc7PnCRiU5eylJOeYs46IEX4iTRswrkuB42Eo18bmw4e7CeVq5q03MHz1fAKtCGljV0wGONTZRCqk4heUlsyiwyp8R8Uib4SEs4/CHA/rjjUc8PE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
